<?php

/**
 * Auto-generated by generate_drush_script.py
 * Run with: drush scr <this-file>
 *
 * Creates a single 'tour' node from parsed markdown field data.
 * Review the taxonomy vocabulary machine names below before running —
 * they are guesses based on field labels and may need correcting.
 */

// --- Review notes from source markdown (fields left blank or trimmed) ---
// - banner image: kept '' — stripped note _(skipped — set manually in Drupal)_
// - banner image: left blank (not stated in source)
// - tour type: kept 'Pilgrimage & Nature' — stripped note (⚠️ new term)
// - season: kept '' — stripped note _(not stated)_
// - season: left blank (not stated in source)
// - inclusions: kept 'Hotel Accommodation, All Meals — Breakfast, Lunch & Dinner' — stripped note (⚠️ new term), Sightseeing Entry Fees (⚠️ new term), Drinking Water — 2 Litres per Person per Day (⚠️ new term), All Transportation (⚠️ new term)
// - journey date: kept '' — stripped note _(not stated)_
// - journey date: left blank (not stated in source)
// - group size: kept '' — stripped note _(not stated)_
// - group size: left blank (not stated in source)
// - group type: kept '' — stripped note _(not stated)_
// - group type: left blank (not stated in source)
// - additional notes (not part of drupal fields): kept '- Tour Cost: ₹11,750/- per head + train ticket' — stripped note (excluded)

$values = [
  'type' => 'tour',
  'title' => 'Keonjhar Temple & Waterfall Trail',
  'status' => 1,
  'uid' => 1,
];

$node = \Drupal\node\Entity\Node::create($values);

$node->set('field_location', 'Keonjhar, Odisha, India');
$node->set('field_duration', '5 Days / 4 Nights');
// season (field_season) left blank — not provided in source.
// journey date (field_journey_date) left blank — not provided in source.
// group size (field_group_size) left blank — not provided in source.
$node->set('field_source', 'Howrah');
$node->set('field_destination', 'Jajpur Keonjhar Road');
// group type (field_group_type) left blank — not provided in source.
$node->set('field_body', ['value' => 'Discover the sacred temples and hidden waterfalls of Keonjhar on this immersive 5-day journey through Odisha\'s countryside. From the revered Maa Tarini Temple to the cascading beauty of Barha Ghaghra and Khandadhar Waterfalls, this trip blends spirituality, nature, and relaxation. Comfortable hotel stays, all meals, and hassle-free transportation make it a perfect getaway for a refreshing break.', 'format' => 'basic_html']);

/**
 * Loads an existing taxonomy term by name in the given vocabulary,
 * or creates it if it doesn't exist.
 */
function _tour_get_or_create_term(string $name, string $vocabulary): ?int {
  $name = trim($name);
  if ($name === '') {
    return NULL;
  }
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
    'name' => $name,
    'vid' => $vocabulary,
  ]);
  if (!empty($terms)) {
    return (int) reset($terms)->id();
  }
  $term = \Drupal\taxonomy\Entity\Term::create([
    'name' => $name,
    'vid' => $vocabulary,
  ]);
  $term->save();
  \Drupal::logger('tour_node_creator')->notice('Created new taxonomy term %name in %vocab.', ['%name' => $name, '%vocab' => $vocabulary]);
  return (int) $term->id();
}

$_tid = _tour_get_or_create_term('National', 'tour_categories');
if ($_tid) { $node->set('field_tour_category', ['target_id' => $_tid]); }

$_tid = _tour_get_or_create_term('Pilgrimage & Nature', 'tour_types');
if ($_tid) { $node->set('field_tour_type', ['target_id' => $_tid]); }

$_field_inclusions_names = ["Hotel Accommodation", "All Meals \u2014 Breakfast, Lunch & Dinner", "Sightseeing Entry Fees", "Drinking Water \u2014 2 Litres per Person per Day", "All Transportation"];
$_field_inclusions_tids = [];
foreach ($_field_inclusions_names as $_name) {
  $_tid = _tour_get_or_create_term($_name, 'tour_inclusions');
  if ($_tid) { $_field_inclusions_tids[] = ['target_id' => $_tid]; }
}
$node->set('field_inclusions', $_field_inclusions_tids);

// Itinerary: one 'Itinerary Day' paragraph per day.
$_itinerary_items = [];
$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Arrival in Keonjhar',
  'field_day_description' => ['value' => 'Board train no. 12821 from Howrah at 9:10 AM and travel to Jajpur Keonjhar Road station. On arrival, check in to the hotel and settle in for a relaxing overnight stay.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Temples & Waterfalls Sightseeing',
  'field_day_description' => ['value' => 'After breakfast, set out for a day of local sightseeing covering the sacred Maa Tarini Temple, the scenic Gundicha Waterfall, Bhim Kund, the historic Sitabinji rock shelter, and Kanjhari Dam. Return to the hotel for dinner and an overnight stay.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Waterfall Exploration',
  'field_day_description' => ['value' => 'After breakfast, head out to explore Bada Ghaghra Waterfall, Gupta Ganga, and the majestic Khandadhar Waterfall. Return to the hotel in the evening for a comfortable overnight stay.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Leisure & Celebration',
  'field_day_description' => ['value' => 'Enjoy a relaxed half-day of local sightseeing after breakfast, followed by free time to unwind. In the evening, join a fun night party at the hotel before settling in for the night.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Departure',
  'field_day_description' => ['value' => 'After breakfast, check out from the hotel and transfer to Jajpur Keonjhar Road station for the return journey. Board train no. 12822, departing at 11:36 AM and arriving in Howrah at 6:20 PM.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$node->set('field_itinerary', $_itinerary_items);

$node->save();

echo 'Created tour node: ' . $node->id() . "\n";
