<?php

/**
 * Auto-generated by generate_drush_script.py
 * Run with: drush scr <this-file>
 *
 * Creates a single 'tour' node from parsed markdown field data.
 * Review the taxonomy vocabulary machine names below before running —
 * they are guesses based on field labels and may need correcting.
 */

// --- Review notes from source markdown (fields left blank or trimmed) ---
// - banner image: kept '' — stripped note _(skipped — set manually in Drupal)_
// - banner image: left blank (not stated in source)
// - tour type: kept 'Wildlife & Heritage' — stripped note (⚠️ new term — not in existing taxonomy; closest existing options are "Family & Couple" or "Adventure", but neither fits this itinerary well)
// - season: kept '' — stripped note _(not stated)_
// - season: left blank (not stated in source)
// - inclusions: kept 'Flight Tickets, Hotel Accommodation, Daily Breakfast, Airport or Station Transfers' — stripped note _(Train Tickets explicitly excluded per source)_
// - journey date: kept '' — stripped note _(not stated)_
// - journey date: left blank (not stated in source)
// - group size: kept '' — stripped note _(not stated)_
// - group size: left blank (not stated in source)
// - destination: kept 'Satna / Indore' — stripped note _(two-leg journey — outbound via Satna, return via Indore; please confirm which to use if the field only accepts one value)_
// - group type: kept 'Family' — stripped note _(inferred from adult/child pricing tiers in source — please confirm)_

$values = [
  'type' => 'tour',
  'title' => 'Madhya Pradesh Heritage & Wildlife Tour',
  'status' => 1,
  'uid' => 1,
];

$node = \Drupal\node\Entity\Node::create($values);

$node->set('field_location', 'Madhya Pradesh, India');
$node->set('field_duration', '16 Days / 15 Nights');
// season (field_season) left blank — not provided in source.
// journey date (field_journey_date) left blank — not provided in source.
// group size (field_group_size) left blank — not provided in source.
$node->set('field_source', 'Howrah');
$node->set('field_destination', 'Satna / Indore');
$node->set('field_group_type', 'Family');
$node->set('field_body', ['value' => 'Discover the timeless temples, wildlife reserves, and hill stations of Madhya Pradesh on this immersive 16-day journey. From the intricately carved temples of Khajuraho and the wild trails of Bandhavgarh to the sacred waters of Amarkantak and the scenic charm of Panchmarhi, this tour weaves together heritage, nature, and spirituality. The journey concludes with visits to Bhopal, Sanchi, Ujjain, and Mandu before returning home.', 'format' => 'basic_html']);

/**
 * Loads an existing taxonomy term by name in the given vocabulary,
 * or creates it if it doesn't exist.
 */
function _tour_get_or_create_term(string $name, string $vocabulary): ?int {
  $name = trim($name);
  if ($name === '') {
    return NULL;
  }
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
    'name' => $name,
    'vid' => $vocabulary,
  ]);
  if (!empty($terms)) {
    return (int) reset($terms)->id();
  }
  $term = \Drupal\taxonomy\Entity\Term::create([
    'name' => $name,
    'vid' => $vocabulary,
  ]);
  $term->save();
  \Drupal::logger('tour_node_creator')->notice('Created new taxonomy term %name in %vocab.', ['%name' => $name, '%vocab' => $vocabulary]);
  return (int) $term->id();
}

$_tid = _tour_get_or_create_term('National', 'tour_categories');
if ($_tid) { $node->set('field_tour_category', ['target_id' => $_tid]); }

$_tid = _tour_get_or_create_term('Wildlife & Heritage', 'tour_types');
if ($_tid) { $node->set('field_tour_type', ['target_id' => $_tid]); }

$_field_inclusions_names = ["Flight Tickets", "Hotel Accommodation", "Daily Breakfast", "Airport or Station Transfers"];
$_field_inclusions_tids = [];
foreach ($_field_inclusions_names as $_name) {
  $_tid = _tour_get_or_create_term($_name, 'tour_inclusions');
  if ($_tid) { $_field_inclusions_tids[] = ['target_id' => $_tid]; }
}
$node->set('field_inclusions', $_field_inclusions_tids);

// Itinerary: one 'Itinerary Day' paragraph per day.
$_itinerary_items = [];
$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Departure from Howrah',
  'field_day_description' => ['value' => 'Depart from Howrah at 11:40 PM by the Mumbai Mail (via Allahabad), setting off on your Madhya Pradesh adventure.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Arrival at Satna & Transfer to Khajuraho',
  'field_day_description' => ['value' => 'Arrive at Satna in the afternoon and transfer to Khajuraho, where you\'ll check in for an overnight stay.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Khajuraho Sightseeing',
  'field_day_description' => ['value' => 'Spend the full day exploring the magnificent temples and heritage sites of Khajuraho, famed for their intricate carvings. Overnight stay in Khajuraho.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Khajuraho to Bandhavgarh',
  'field_day_description' => ['value' => 'After breakfast, depart Khajuraho at 8:00 AM and arrive at Bandhavgarh by evening, with lunch en route. Overnight stay in Bandhavgarh.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Bandhavgarh Safari & Onward to Amarkantak',
  'field_day_description' => ['value' => 'Enjoy an early morning jeep safari through Bandhavgarh National Park (entry, camera, guide, and jeep charges payable directly). After lunch, depart for Amarkantak, arriving in the evening for an overnight stay.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Amarkantak Sightseeing & Transfer to Jabalpur',
  'field_day_description' => ['value' => 'After breakfast, explore Amarkantak\'s sacred sites including Dudh Dhara, Kapil Dhara, the source of the Narmada River, and Sonmuda, before transferring to Jabalpur for the night.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Jabalpur Sightseeing',
  'field_day_description' => ['value' => 'Visit Jabalpur\'s iconic Marble Rocks, the 64 Yogini Temple, and Dhuandhar Falls in the morning, returning by early afternoon. Overnight stay in Jabalpur.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Jabalpur to Panchmarhi',
  'field_day_description' => ['value' => 'Depart Jabalpur early morning and arrive in Panchmarhi by late afternoon, with breakfast and lunch en route. Overnight stay in Panchmarhi.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Panchmarhi Sightseeing',
  'field_day_description' => ['value' => 'A full day exploring Panchmarhi\'s natural beauty — Jata Shankar, Pandav Caves, Priyadarshini Point, and Mahadev in the morning; Bee Falls and Rajendra Giri Sunset Point in the afternoon. Overnight stay in Panchmarhi.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Panchmarhi to Bhopal via Bhimbetka',
  'field_day_description' => ['value' => 'Depart Panchmarhi and travel to Bhopal via the prehistoric rock shelters of Bhimbetka, with breakfast and lunch on the way. Overnight stay in Bhopal.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Sanchi & Bhopal Sightseeing',
  'field_day_description' => ['value' => 'Visit the ancient Buddhist stupas of Sanchi in the morning, then explore Bhopal\'s Zoo and Birla Temple in the afternoon. Overnight stay in Bhopal.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Bhopal to Indore via Ujjain',
  'field_day_description' => ['value' => 'Travel from Bhopal to Indore, stopping en route at Ujjain to visit the sacred Mahakaleshwar Temple. Overnight stay in Indore.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Mandu Excursion',
  'field_day_description' => ['value' => 'A day trip to the historic city of Mandu, returning to Indore by evening. Overnight stay in Indore.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Omkareshwar & Departure from Indore',
  'field_day_description' => ['value' => 'After lunch, visit the sacred island temple of Omkareshwar before transferring to Indore Railway Station for your evening departure by Shipra Express.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Journey Home',
  'field_day_description' => ['value' => 'A relaxing day aboard the train as you make your way back to Howrah.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$_p = \Drupal\paragraphs\Entity\Paragraph::create([
  'type' => 'itinerary_day',
  'field_day_title' => 'Arrival at Howrah',
  'field_day_description' => ['value' => 'Arrive in Howrah at 6:40 AM, marking the end of a memorable Madhya Pradesh journey.', 'format' => 'basic_html'],
]);
$_p->save();
$_itinerary_items[] = ['target_id' => $_p->id(), 'target_revision_id' => $_p->getRevisionId()];

$node->set('field_itinerary', $_itinerary_items);

$node->save();

echo 'Created tour node: ' . $node->id() . "\n";